# patterns for all video tags
pattern.video.tags: (?:Special.|Extended.|Ultimate.)?(?:Director.?s|Collector.?s|Theatrical|Ultimate|Final|Extended|Rogue|Special|Diamond|Despecialized|R.Rated|Super.Duper|(?:(?:1st|2nd|3rd|[4-9]th).)?Anniversary).(?:Cut|Edition|Version)|Extended|Theatrical|Remastered|Recut|Uncut|Uncensored|Censored|Unrated|IMAX|Alternate.Ending|Open.Matte

# patterns for stereoscopic 3D tags
pattern.video.s3d: (?:(?:H|HALF|F|FULL)[\\P{Alnum}]{0,2})?(?:SBS|TAB|OU)

# patterns for repack tags
pattern.video.repack: REPACK|PROPER|RERIP

# patterns for all subtitle tags
pattern.subtitle.tags: forced|HI|CC|SDH

# additional release info patterns
pattern.video.format: The.[0-9]{3,4}\\b|DivX[345]?|Xvid|AVC|[xh][.]?(?:264|265)|HEVC|dxva|3ivx|PGS|MP[E]?G[45]?|HDR[+0-9]*|DV|DoVi|Dolby.Vision|(?:Multi.)?(?:FLAC|AAC|AC3|MP3|MP4|DTS|TrueHD|DTheater|\\bDD)(?:[. ]?(?:HD|P|[+]))?(?:[. \\-\\(]*(?:Atmos|HRA|HD|MA|ES|EX|X\\b))?(?:[. \\)]*[1-9][. ]?[01])?|[1-9]ch|FLAC(?:x[2-3])?|AAC|AC3|MP3|MP4|TrueHD|Atmos|(?:HD|BD)?[M0]?(?:480|576|720|1080|2160|4320)[pix]+(?:60)?|(?<=[-])(?:2D|3D|480|576|720|1080|2160|4320)|(?:7680|3840|2040|1920|1280|720|640)x[0-9]{3,4}|(?:8|10).?bit|(?:24|30|60)FPS|Hi10[P]?|[A-Z]{2,3}.(?:[257][.][01])|(?:19|20)[0-9]+.S[0-9]+(?!.?E[0-9]+)|(?<=[0-9]+)v[0-4]|\\bCD[0-9]+\\b

# clutter file exclude pattern
pattern.clutter.excludes: (?<=[!\\-\\(\\[])(?:Sample|Trailer)|(?:Sample|Trailer)(?=[\\-\\)\\]])|(?<=[.\\-]|^)(?:(?-i:s|t)|sample|trailer|deleted|featurette|interview|scene|other|behindthescene)$|(?:NCED|NCOP|(?-i:OP|ED)\\d{0,2}(?!\\p{Alnum}))|(?:Extras|Trailers|Featurettes|Interviews|Scenes)$|Behind.the.Scenes|Deleted.and.Extended.Scenes|Deleted.Scenes

# clutter file pattern
pattern.clutter.file: [\\-](?:behindthescenes|deleted|featurette|interview|scene|short|trailer|other)[.][^.]+$

# clutter folder pattern
pattern.clutter.folder: Extras|Trailers|Featurettes|Interviews|Scenes|Shorts|Behind.the.Scenes|Deleted.Scenes

# clutter file types
pattern.clutter.types: [.](?:jpg|jpeg|png|gif|ico|nfo|info|xml|htm|html|log|m3u|cue|ffp|srt|sub|idx|smi|sup|md5|sfv|txt|rtf|url|website|db|dna|log|tgmd|json|data|ignore|srv|srr|nzb|vbs|ini|vsmeta|DS_Store)$

# disk folder matcher
pattern.diskfolder.entry: BDMV|AVCHD|HVDVD_TS|VIDEO_TS|AUDIO_TS|VCD|MovieObject.bdmv|VIDEO_TS.VOB|VTS_[0-9]+_[0-9]+.VOB

# media root folders
folder.media.roots: /Volumes:/Users:/home:/mnt:/media

# system file pattern
pattern.system.files: [.@][a-z]+|#recycle|bin|initrd|opt|sbin|var|dev|lib|proc|sys|var.defaults|etc|lost.found|root|tmp|etc.defaults|mnt|run|usr|System.Volume.Information
