application.name: FileBot
application.version: 5.2.3
application.revision: 10990

update.url: https://app.filebot.net/update.xml
github.master: https://raw.githubusercontent.com/filebot/scripts/master/

link.review.mas: macappstore://apps.apple.com/app/id905384638?action=write-review
link.review.mws: ms-windows-store://review/?ProductId=9NBLGGH52T9X

link.app.help: https://www.filebot.net/getting-started/embed.html
link.app.purchase: https://www.filebot.net/purchase.html

link.intro: https://www.filebot.net/getting-started/index.html
link.activate: https://www.filebot.net/activate.html
link.forums: https://www.filebot.net/forums/
link.faq: https://www.filebot.net/manual.html
link.bugs: https://www.filebot.net/report.html
link.channel: https://www.filebot.net/channel.html
link.help: https://www.filebot.net/support.html
link.help.presets: @{link.help.presets}
link.help.manpage: https://www.filebot.net/manpage.html
