package net.filemaid.hash;

import java.io.Closeable;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.Charset;
import java.util.Date;
import net.filemaid.Settings;
import net.filemaid.hash.VerificationFormat;

public class VerificationFileWriter
implements Closeable {
    protected PrintWriter out;
    protected VerificationFormat format;

    public VerificationFileWriter(File file, VerificationFormat verificationFormat, Charset charset) throws IOException {
        this(new FileOutputStream(file), verificationFormat, charset);
    }

    public VerificationFileWriter(OutputStream outputStream, VerificationFormat verificationFormat, Charset charset) throws IOException {
        this(new PrintWriter(new OutputStreamWriter(outputStream, charset), false), verificationFormat, charset);
    }

    public VerificationFileWriter(PrintWriter printWriter, VerificationFormat verificationFormat, Charset charset) {
        this.out = printWriter;
        this.format = verificationFormat;
        this.writeHeader(charset);
    }

    protected void writeHeader(Charset charset) {
        this.out.format("; Generated by %s %s on %tF at %<tT%n", Settings.getApplicationName(), Settings.getApplicationVersion(), new Date());
        this.out.format("; charset=%s%n", charset);
        this.out.format(";%n", new Object[0]);
    }

    public void write(String string, String string2) {
        this.out.format("%s%n", this.format.format(string, string2));
    }

    @Override
    public void close() throws IOException {
        this.out.close();
    }
}

