# Use system look and feel:
# net.filebot.theme=System

# Use custom UI scale factor:
# sun.java2d.uiScale=2

# Use custom font family and font size:
# net.filebot.theme.font=Tahoma
# net.filebot.theme.font.size=14

# Use fail-safe file chooser:
# net.filebot.UserFiles.fileChooser=Swing

# Drop files in selection order:
# net.filebot.dnd.sort=false

# Disable blur effect:
# net.filebot.glass.effect=false

# Use OpenGL graphics pipeline:
# sun.java2d.opengl=true

# Disable media parser:
# net.filebot.media.parser=none

# Enable file name heuristics:
# net.filebot.files.heuristics=true

# Use .xattr folders to store metadata
# net.filebot.xattr.store=.xattr

# Disable persistent MediaInfo and CRC32 cache
# net.filebot.xattr.cache=false

# Disable recycle bin:
# net.filebot.UserFiles.trash=Delete

# Create symlinks with absolute paths
# net.filebot.symlink=absolute

# Disable file path validation:
# unixfs=true

# Disable Windows shell integration:
# useNativeShell=false

# Configure parallel processing limits:
# parallelism=8..64

# Configure process priority:
# priority=1

# Disable media index:
# net.filebot.media.index=false

# Configure maximum media depth:
# net.filebot.media.depth=1

# Configure clutter file heuristics:
# net.filebot.media.clutter.size=10
# net.filebot.media.clutter.length=PT1M

# Configure external tools:
# net.filebot.postprocess.mkvpropedit=C:/Tools/mkvpropedit.exe
# net.filebot.postprocess.AtomicParsley=C:/Tools/AtomicParsley.exe

# Use IPv4 network stack:
# java.net.preferIPv4Stack=true

# Use HTTP/1 network protocol:
# net.filebot.web.WebRequest.v1=true

# Disable system proxy:
# java.net.useSystemProxies=false

# Configure HTTP proxy:
# http.proxyHost=127.0.0.1
# http.proxyPort=7890
# https.proxyHost=127.0.0.1
# https.proxyPort=7890

# Configure SOCKS proxy:
# socksProxyHost=127.0.0.1
# socksProxyPort=1080

# Enable debug logging:
# net.filebot.logging.debug=ALL
# net.filebot.logging.time=true
